# ----------------------------------- Basic ---------------------------------- #

title: Start
email: intia@th-koeln.de
description: >- # this means to ignore newlines until "baseurl:"
  A plattform for methods, techniques, toolkits and patterns for participative development in a social context.
baseurl: ""
url: ""

# ----------------------------------- Theme ---------------------------------- #

theme: null
footer_menu: footer

# ---------------------------------- Plugins --------------------------------- #

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-relative-links
  - jekyll-avatar
  - jekyll-coffeescript
  - jekyll-commonmark
  - jekyll-commonmark-ghpages
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-mentions
  - jekyll-optional-front-matter
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-sass-converter
  - jekyll-titles-from-headings
  - jekyll-watch
github: [metadata]
sass:
  style: compressed

# Pagination
paginate: 3
paginate_path: "/stories/page:num"

# ------------------------- Defaults and Collections ------------------------- #

# Defaults
defaults:
  - scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      hide_hero: false
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
      permalink: /stories/:title/
  - scope:
      type: pages
      path: pages
    values:
      is_post: false
      layout: page
      show_sidebar: true

# Collections
collections_dir: collections
collections:
  building_blocks:
    output: true
    image: https://via.placeholder.com/800x600
    show_sidebar: false
  methods:
    output: true
  glossary:
    output: true
    show_sidebar: false

# --------------------------- Includes and Excludes -------------------------- #

# Include
include:
  - CNAME

# Exclude from processing.
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
