title: INTIA
email: intia@th-koeln.de
description: >- # this means to ignore newlines until "baseurl:"
  A plattform for methods, techniques, toolkits and pattern for participative development in a social context.
baseurl: ""
url: ""
theme: null
# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - kramdown-parser-gfm
  - jekyll-relative-links
permalink: pretty
github: [metadata]
sass:
  style: compressed

## Content Settings
# Default frontmatter
defaults:    
  -
    scope:
      type: posts
      path: _posts
    values:
      is_post: true
      layout: post
      image: https://via.placeholder.com/1200x800
      show_sidebar: true
      permalink: /stories/:title/
  -
    scope:
      type: pages
      path: pages
    values:
      is_post: false
      layout: page
      show_sidebar: true  

paginate: 5
paginate_path: "/stories/page:num"

footer_menu: footer

collections:
  products: 
    output: true
    layout: product
    image: https://via.placeholder.com/800x600
    show_sidebar: false